### ISSUE TITLE
Error on env.render()

### ISSUE THREAD

**Issue by colinskow** [simontudo/vizdoomgym#2]
```python
import gym
import vizdoomgym
env = gym.make("VizdoomBasic-v0")
env.reset()
env.render()
env.env.close()
```
Generates the error:
```
Exception ignored in: <bound method SimpleImageViewer.__del__ of <gym.envs.classic_control.rendering.SimpleImageViewer object at 0x7fa15f523a90>>
Traceback (most recent call last):
  File "/home/colin/py3/lib/python3.6/site-packages/gym/envs/classic_control/rendering.py", line 359, in __del__
  File "/home/colin/py3/lib/python3.6/site-packages/gym/envs/classic_control/rendering.py", line 355, in close
  File "/home/colin/py3/lib/python3.6/site-packages/pyglet/window/xlib/__init__.py", line 480, in close
  File "/home/colin/py3/lib/python3.6/site-packages/pyglet/gl/xlib.py", line 345, in destroy
  File "/home/colin/py3/lib/python3.6/site-packages/pyglet/gl/base.py", line 334, in destroy
  File "/home/colin/py3/lib/python3.6/site-packages/pyglet/gl/xlib.py", line 335, in detach
  File "/home/colin/py3/lib/python3.6/site-packages/pyglet/gl/lib.py", line 97, in errcheck
ImportError: sys.meta_path is None, Python is likely shutting down
```

**Comment by shakenes** [comment]
Sorry for not answering, I didn't work on this project anymore. Anyway, I cannot reproduce your error (it should be `env.close()` btw).
